export interface OrganizationLogo {
  id: string;
  name: string;
  shortName?: string;
  industryId: 'finance' | 'real-estate' | 'tech-edu' | 'media' | 'fmcg' | 'logistics' | 'retail';
  industryName: string;
  tier: 1 | 2;
  caseStudySlug?: string;
  brandColor: string;
  brandBg: string;
  textLogo: string;
  description: string;
}

export interface IndustryFilter {
  id: string;
  name: string;
  count?: number;
}

export const INDUSTRY_FILTERS: IndustryFilter[] = [
  { id: 'all', name: 'Tất Cả Ngành' },
  { id: 'finance', name: 'Tài Chính · Chứng Khoán · Bảo Hiểm' },
  { id: 'real-estate', name: 'Bất Động Sản · Năng Lượng' },
  { id: 'tech-edu', name: 'Công Nghệ · Giáo Dục Đại Học' },
  { id: 'media', name: 'Truyền Thông · Sáng Tạo' },
  { id: 'fmcg', name: 'FMCG · F&B · Dược Phẩm' },
  { id: 'logistics', name: 'Vận Tải · Logistics · Phân Phối' },
  { id: 'retail', name: 'Bán Lẻ Chuỗi & Thương Mại' },
];

export const ORGANIZATION_LOGOS: OrganizationLogo[] = [
  // 1. Vietcap Securities
  {
    id: 'vietcap',
    name: 'Vietcap Securities (VCI)',
    shortName: 'Vietcap',
    industryId: 'finance',
    industryName: 'Tài Chính & Chứng Khoán',
    tier: 1,
    caseStudySlug: 'vietcap-ai-multi-agent-nghien-cuu-thi-truong',
    brandColor: '#005596',
    brandBg: '#F0F5FA',
    textLogo: 'Vietcap',
    description: 'Thiết lập hệ thống Multi-Agent bóc tách BCTC tự động cho 30+ chuyên viên, giảm 75% thời gian xử lý.',
  },
  // 2. Vinhomes
  {
    id: 'vinhomes',
    name: 'Vinhomes (Vingroup)',
    shortName: 'Vinhomes',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 1,
    caseStudySlug: 'vinhomes-ai-sales-enablement',
    brandColor: '#8B6F3E',
    brandBg: '#FBF8F3',
    textLogo: 'VINHOMES',
    description: 'Đào tạo AI Sales Enablement & Lead Reactivation cho 500+ nhân sự kinh doanh và phân phối BĐS.',
  },
  // 3. FPT University
  {
    id: 'fptu',
    name: 'Đại học FPT (FPTU)',
    shortName: 'ĐH FPT',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 1,
    caseStudySlug: 'fptu-nang-bac-giang-vien-ai',
    brandColor: '#F37021',
    brandBg: '#FEF5EE',
    textLogo: 'FPTU',
    description: 'Đào tạo nâng bậc GV chuẩn Bậc 6 & Điều phối MC ảo và AI Agents tại Tech Fest với 10.000+ người tham gia.',
  },
  // 4. Dentsu Sports Vietnam
  {
    id: 'dentsu',
    name: 'Dentsu Sports & Creative',
    shortName: 'Dentsu',
    industryId: 'media',
    industryName: 'Truyền Thông & Sáng Tạo',
    tier: 1,
    caseStudySlug: 'dentsu-ai-pitch-deck-automation',
    brandColor: '#002D62',
    brandBg: '#EFF4F9',
    textLogo: 'dentsu',
    description: 'Rút ngắn 65% thời gian phát triển proposal đấu thầu tài trợ thể thao quốc tế bằng quy trình AI chuẩn hóa.',
  },
  // 5. VNPT VinaPhone
  {
    id: 'vnpt',
    name: 'VNPT VinaPhone',
    shortName: 'VNPT',
    industryId: 'tech-edu',
    industryName: 'Viễn Thông & Dịch Vụ Số',
    tier: 1,
    caseStudySlug: 'vnpt-ai-content-video-automation',
    brandColor: '#0066B2',
    brandBg: '#EDF5FC',
    textLogo: 'VNPT',
    description: 'Tăng gấp 3 lần sản lượng nội dung truyền thông số và video ngắn giới thiệu gói cước tự động.',
  },
  // 6. Phương Trường An Group
  {
    id: 'phuong-truong-an',
    name: 'Phương Trường An Group',
    shortName: 'Phương Trường An',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 1,
    caseStudySlug: 'phuong-truong-an-ai-video-production',
    brandColor: '#0A5C36',
    brandBg: '#EDF7F1',
    textLogo: 'PTA GROUP',
    description: 'Đào tạo sản xuất video hiện trường bằng AI, tăng 200% sản lượng tin bài cho ~300 nhân sự kinh doanh.',
  },
  // 7. Trương Đoàn Marketing Group
  {
    id: 'truong-doan',
    name: 'Trương Đoàn Marketing Group',
    shortName: 'Trương Đoàn',
    industryId: 'media',
    industryName: 'Tiếp Thị & Activation',
    tier: 1,
    caseStudySlug: 'truong-doan-ai-activation-qc',
    brandColor: '#E02B20',
    brandBg: '#FDF1F0',
    textLogo: 'TRUONG DOAN',
    description: 'Tiết kiệm 70% thời gian duyệt ảnh thực địa activation và rút ngắn phản hồi brief từ 3 ngày xuống 4 giờ.',
  },
  // 8. Đài Truyền Hình TP.HCM (HTV)
  {
    id: 'htv',
    name: 'Đài Truyền Hình TP.HCM (HTV)',
    shortName: 'HTV',
    industryId: 'media',
    industryName: 'Truyền Hình & Phát Thanh',
    tier: 1,
    brandColor: '#0088CC',
    brandBg: '#EDF8FD',
    textLogo: 'HTV',
    description: 'Rút ngắn 50% thời gian sản xuất đồ họa trường quay ảo và tự động hóa dựng trailer phát sóng.',
  },
  // 9. Smartland Bất Động Sản
  {
    id: 'smartland',
    name: 'Smartland Bất Động Sản',
    shortName: 'Smartland',
    industryId: 'real-estate',
    industryName: 'Phân Phối BĐS Cao Cấp',
    tier: 1,
    brandColor: '#B8860B',
    brandBg: '#FDFBF0',
    textLogo: 'SMARTLAND',
    description: 'Tự động hóa 80% khâu tương tác ban đầu với khách hàng tiềm năng dự án căn hộ cao cấp qua AI Agents.',
  },
  // 10. Vietcombank
  {
    id: 'vietcombank',
    name: 'Vietcombank',
    shortName: 'VCB',
    industryId: 'finance',
    industryName: 'Ngân Hàng Thương Mại',
    tier: 2,
    brandColor: '#005C2B',
    brandBg: '#EDF7F1',
    textLogo: 'Vietcombank',
    description: 'Cán bộ quản lý & chuyên viên dữ liệu tham gia đào tạo rà soát hồ sơ tín dụng và bóc tách BCTC bằng AI.',
  },
  // 11. BIDV
  {
    id: 'bidv',
    name: 'BIDV',
    shortName: 'BIDV',
    industryId: 'finance',
    industryName: 'Ngân Hàng Thương Mại',
    tier: 2,
    brandColor: '#194B73',
    brandBg: '#EFF5F9',
    textLogo: 'BIDV',
    description: 'Cán bộ tín dụng tham gia đào tạo chuẩn hóa báo cáo thẩm định điều kiện cấp tín dụng doanh nghiệp.',
  },
  // 12. Prudential Vietnam
  {
    id: 'prudential',
    name: 'Prudential Vietnam',
    shortName: 'Prudential',
    industryId: 'finance',
    industryName: 'Bảo Hiểm Nhân Thọ',
    tier: 2,
    brandColor: '#ED1B2D',
    brandBg: '#FDF1F2',
    textLogo: 'PRUDENTIAL',
    description: 'Mạng lưới tư vấn viên tham gia chương trình đào tạo AI tra cứu quyền lợi và cá nhân hóa kịch bản bảo hiểm.',
  },
  // 13. Dai-ichi Life Vietnam
  {
    id: 'dai-ichi',
    name: 'Dai-ichi Life Vietnam',
    shortName: 'Dai-ichi Life',
    industryId: 'finance',
    industryName: 'Bảo Hiểm Nhân Thọ',
    tier: 2,
    brandColor: '#D4001F',
    brandBg: '#FCEEF0',
    textLogo: 'DAI-ICHI',
    description: 'Khóa đào tạo AI for Consultants giúp tư vấn viên tăng 40% tỷ lệ hẹn gặp khách hàng thành công.',
  },
  // 14. Trung Sơn Pharma
  {
    id: 'trung-son',
    name: 'Trung Sơn Pharma',
    shortName: 'Trung Sơn',
    industryId: 'fmcg',
    industryName: 'Chuỗi Bán Lẻ Dược Phẩm',
    tier: 1,
    brandColor: '#0077C8',
    brandBg: '#EDF6FC',
    textLogo: 'TRUNG SƠN',
    description: 'Tư vấn thiết kế hệ thống Omnichannel Marketing & CRM chuỗi nhà thuốc từ giai đoạn mở rộng mạng lưới.',
  },
  // 15. FSI Digital
  {
    id: 'fsi',
    name: 'FSI Digital',
    shortName: 'FSI',
    industryId: 'tech-edu',
    industryName: 'Chuyển Đổi Số & Dữ Liệu',
    tier: 2,
    brandColor: '#004B87',
    brandBg: '#EEF4F9',
    textLogo: 'FSI',
    description: 'Nhân sự tham gia chương trình đào tạo AI trong số hóa dữ liệu và xử lý văn bản phi cấu trúc.',
  },
  // 16. Droppii Commerce
  {
    id: 'droppii',
    name: 'Droppii Commerce',
    shortName: 'Droppii',
    industryId: 'tech-edu',
    industryName: 'Thương Mại Điện Tử Tư Vấn',
    tier: 2,
    brandColor: '#FF5500',
    brandBg: '#FEF4EE',
    textLogo: 'droppii',
    description: 'Đào tạo AI ứng dụng trong tự động hóa kịch bản tư vấn và sáng tạo nội dung livestream thương mại.',
  },
  // 17. UEF
  {
    id: 'uef',
    name: 'Đại học Kinh tế - Tài chính TP.HCM (UEF)',
    shortName: 'UEF',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 2,
    brandColor: '#C8102E',
    brandBg: '#FCF0F2',
    textLogo: 'UEF',
    description: 'Tổ chức các chuyên đề AI thực chiến và đào tạo kỹ năng ứng dụng công nghệ cho sinh viên & giảng viên.',
  },
  // 18. NTTU
  {
    id: 'nttu',
    name: 'Đại học Nguyễn Tất Thành (NTTU)',
    shortName: 'NTTU',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 2,
    brandColor: '#003865',
    brandBg: '#EDF3F8',
    textLogo: 'NTTU',
    description: 'Hợp tác chuyển giao kiến thức AI thực hành và xây dựng kỹ năng công nghệ chuẩn bị cho thị trường lao động.',
  },
  // 19. Thắng Lợi Group
  {
    id: 'thang-loi',
    name: 'Thắng Lợi Group',
    shortName: 'Thắng Lợi',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 2,
    brandColor: '#C29B38',
    brandBg: '#FCF9F1',
    textLogo: 'THẮNG LỢI',
    description: 'Chuyên viên kinh doanh tham gia đào tạo AI sáng tạo nội dung dự án và chăm sóc khách hàng tự động.',
  },
  // 20. Huỳnh Anh Group
  {
    id: 'huynh-anh',
    name: 'Huỳnh Anh Group',
    shortName: 'Huỳnh Anh',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 2,
    brandColor: '#2E5B88',
    brandBg: '#F0F4F8',
    textLogo: 'HUỲNH ANH',
    description: 'Đào tạo ứng dụng AI trong quản lý leads và tự động hóa quy trình phân phối sản phẩm bất động sản.',
  },
  // 21. PV Power
  {
    id: 'pv-power',
    name: 'PV Power',
    shortName: 'PV Power',
    industryId: 'real-estate',
    industryName: 'Năng Lượng & Điện Lực',
    tier: 2,
    brandColor: '#007A3D',
    brandBg: '#EDF7F2',
    textLogo: 'PV POWER',
    description: 'Cán bộ kỹ thuật và quản lý tham gia đào tạo phương pháp luận AI trong quản trị dữ liệu vận hành.',
  },
  // 22. Mì Gấu Đỏ
  {
    id: 'gau-do',
    name: 'Mì Gấu Đỏ (Asia Foods)',
    shortName: 'Gấu Đỏ',
    industryId: 'fmcg',
    industryName: 'FMCG & Thực Phẩm',
    tier: 2,
    brandColor: '#E31E24',
    brandBg: '#FDF1F1',
    textLogo: 'GẤU ĐỎ',
    description: 'Cán bộ tiếp thị tham gia chương trình nâng cao năng lực AI trong tiếp thị tiêu dùng và phân tích dữ liệu.',
  },
  // 23. Cháo Cây Thị
  {
    id: 'cay-thi',
    name: 'Cháo Cây Thị',
    shortName: 'Cây Thị',
    industryId: 'fmcg',
    industryName: 'F&B & Thực Phẩm Dinh Dưỡng',
    tier: 2,
    brandColor: '#F37021',
    brandBg: '#FEF5EE',
    textLogo: 'CÂY THỊ',
    description: 'Đào tạo AI ứng dụng trong tối ưu hóa nội dung đa kênh và quản trị thương hiệu chuỗi thực phẩm.',
  },
  // 24. Yến Việt
  {
    id: 'yen-viet',
    name: 'Yến Việt',
    shortName: 'Yến Việt',
    industryId: 'fmcg',
    industryName: 'FMCG & Dinh Dưỡng',
    tier: 2,
    brandColor: '#9A1B24',
    brandBg: '#FAF1F2',
    textLogo: 'YẾN VIỆT',
    description: 'Nhân sự tham gia đào tạo AI trong quản trị phân phối, kiểm soát nội bộ và tiếp thị chuỗi giá trị.',
  },
  // 25. Dr. Muối
  {
    id: 'dr-muoi',
    name: 'Dr. Muối',
    shortName: 'Dr. Muối',
    industryId: 'fmcg',
    industryName: 'Sức Khỏe & Tiêu Dùng',
    tier: 2,
    brandColor: '#00A3E0',
    brandBg: '#EDF9FD',
    textLogo: 'DR. MUỐI',
    description: 'Chuyên viên Marketing tham gia đào tạo AI tự động hóa sản xuất nội dung quảng cáo và video đa kênh.',
  },
  // 26. Hoàng Đức Pharma
  {
    id: 'hoang-duc',
    name: 'Hoàng Đức Pharma',
    shortName: 'Hoàng Đức',
    industryId: 'fmcg',
    industryName: 'Phân Phối Dược Phẩm',
    tier: 2,
    brandColor: '#008542',
    brandBg: '#EDF8F2',
    textLogo: 'HOÀNG ĐỨC',
    description: 'Cán bộ phân phối tham gia đào tạo ứng dụng AI trong chăm sóc mạng lưới đối tác nhà thuốc.',
  },
  // 27. Agrilong
  {
    id: 'agrilong',
    name: 'Agrilong',
    shortName: 'Agrilong',
    industryId: 'fmcg',
    industryName: 'Nông Nghiệp & Vật Tư',
    tier: 2,
    brandColor: '#2E7D32',
    brandBg: '#EFF7F0',
    textLogo: 'AGRILONG',
    description: 'Nhân sự tiếp thị tham gia đào tạo AI xây dựng nội dung truyền thông kỹ thuật nông nghiệp.',
  },
  // 28. VAG International (Poêmy)
  {
    id: 'poemy',
    name: 'VAG International (Poêmy)',
    shortName: 'Poêmy',
    industryId: 'fmcg',
    industryName: 'Dệt May & Tiêu Dùng',
    tier: 2,
    brandColor: '#4A154B',
    brandBg: '#F5EFF5',
    textLogo: 'POÊMY',
    description: 'Đội ngũ bán hàng tham gia đào tạo AI trong sáng tạo hình ảnh sản phẩm và tối ưu hóa sàn TMĐT.',
  },
  // 29. Big Family
  {
    id: 'big-family',
    name: 'Big Family',
    shortName: 'Big Family',
    industryId: 'fmcg',
    industryName: 'Chuỗi Nhà Thuốc',
    tier: 2,
    brandColor: '#D8232A',
    brandBg: '#FCF1F2',
    textLogo: 'BIG FAMILY',
    description: 'Học viên tham gia đào tạo AI hỗ trợ chăm sóc khách hàng và quản trị nội dung tư vấn sức khỏe.',
  },
  // 30. Maison Vie
  {
    id: 'maison-vie',
    name: 'Maison Vie',
    shortName: 'Maison Vie',
    industryId: 'fmcg',
    industryName: 'F&B & Ẩm Thực Cao Cấp',
    tier: 2,
    brandColor: '#8C6239',
    brandBg: '#F9F5F1',
    textLogo: 'MAISON VIE',
    description: 'Cán bộ quản lý ẩm thực tham gia đào tạo AI trong xây dựng trải nghiệm khách hàng và truyền thông ẩm thực.',
  },
  // 31. VACS
  {
    id: 'vacs',
    name: 'VACS (Suất Ăn Hàng Không)',
    shortName: 'VACS',
    industryId: 'logistics',
    industryName: 'Suất Ăn & Logistics Hàng Không',
    tier: 2,
    brandColor: '#003865',
    brandBg: '#EDF3F8',
    textLogo: 'VACS',
    description: 'Nhân sự logistics tham gia đào tạo AI trong chuẩn hóa tài liệu SOP và báo cáo quy trình tác nghiệp.',
  },
  // 32. Mitsubishi Motors
  {
    id: 'mitsubishi',
    name: 'Mitsubishi Motors',
    shortName: 'Mitsubishi',
    industryId: 'logistics',
    industryName: 'Phân Phối Ô Tô',
    tier: 2,
    brandColor: '#E60012',
    brandBg: '#FDF0F1',
    textLogo: 'MITSUBISHI',
    description: 'Chuyên viên đại lý tham gia chương trình đào tạo AI trong chăm sóc khách hàng và tiếp thị số.',
  },
  // 33. QH Distribution
  {
    id: 'qh-dist',
    name: 'QH Distribution',
    shortName: 'QH Dist.',
    industryId: 'logistics',
    industryName: 'Phân Phối Chuỗi',
    tier: 2,
    brandColor: '#1A365D',
    brandBg: '#EEF2F7',
    textLogo: 'QH DIST',
    description: 'Đội ngũ quản lý tham gia đào tạo AI trong phân tích dữ liệu phân phối và quản trị chuỗi cung ứng.',
  },
  // 34. PTEXIM Corp
  {
    id: 'ptexim',
    name: 'PTEXIM Corp',
    shortName: 'PTEXIM',
    industryId: 'logistics',
    industryName: 'Xuất Nhập Khẩu Nông Sản',
    tier: 2,
    brandColor: '#8B0000',
    brandBg: '#F9EEEE',
    textLogo: 'PTEXIM',
    description: 'Cán bộ xuất khẩu tham gia đào tạo AI trong soạn thảo hợp đồng thương mại quốc tế và nghiên cứu thị trường.',
  },
  // 35. Let's Go Taxi
  {
    id: 'lets-go-taxi',
    name: "Let's Go Taxi",
    shortName: "Let's Go",
    industryId: 'logistics',
    industryName: 'Vận Tải Hành Khách',
    tier: 2,
    brandColor: '#F7941D',
    brandBg: '#FEF7F0',
    textLogo: "LET'S GO",
    description: 'Đội ngũ vận hành tham gia đào tạo AI trong xử lý dữ liệu dịch vụ và chăm sóc đối tác tài xế tự động.',
  },
  // 36. JTB-TNT Travel
  {
    id: 'jtb-tnt',
    name: 'JTB-TNT Travel',
    shortName: 'JTB-TNT',
    industryId: 'logistics',
    industryName: 'Du Lịch & Lữ Hành Quốc Tế',
    tier: 2,
    brandColor: '#CC0000',
    brandBg: '#FCEEEE',
    textLogo: 'JTB-TNT',
    description: 'Chuyên viên du lịch tham gia đào tạo AI xây dựng kịch bản tour quốc tế và chăm sóc khách du lịch số.',
  },
  // 37. Golden Gate Group
  {
    id: 'golden-gate',
    name: 'Golden Gate Group',
    shortName: 'Golden Gate',
    industryId: 'fmcg',
    industryName: 'Chuỗi Ẩm Thực F&B',
    tier: 2,
    brandColor: '#B8860B',
    brandBg: '#FDFBF0',
    textLogo: 'GOLDEN GATE',
    description: 'Học viên và chuyên gia tham gia chia sẻ kinh nghiệm ứng dụng AI trong quản trị chuỗi 300+ nhà hàng.',
  },
  // 38. Carlsberg Group
  {
    id: 'carlsberg',
    name: 'Carlsberg Group',
    shortName: 'Carlsberg',
    industryId: 'fmcg',
    industryName: 'Đồ Uống & Tiêu Dùng',
    tier: 2,
    brandColor: '#006F42',
    brandBg: '#ECF6F1',
    textLogo: 'Carlsberg',
    description: 'Học viên và cố vấn tham gia chia sẻ phương pháp luận AI trong quản trị thương hiệu đồ uống toàn cầu.',
  },
  // 39. Central Retail Vietnam
  {
    id: 'central-retail',
    name: 'Central Retail Vietnam',
    shortName: 'Central Retail',
    industryId: 'retail',
    industryName: 'Bán Lẻ Chuỗi & Đại Siêu Thị',
    tier: 2,
    brandColor: '#E4002B',
    brandBg: '#FDF0F2',
    textLogo: 'CENTRAL',
    description: 'Học viên nhân sự tham gia chương trình đào tạo AI trong tối ưu hóa chi phí tuyển dụng và quản trị nhân tài.',
  },
  // 40. Lotte Shopping
  {
    id: 'lotte',
    name: 'Lotte Shopping',
    shortName: 'Lotte',
    industryId: 'retail',
    industryName: 'Bán Lẻ & Trung Tâm Thương Mại',
    tier: 2,
    brandColor: '#ED1C24',
    brandBg: '#FDF1F2',
    textLogo: 'LOTTE',
    description: 'Học viên tham gia đào tạo AI trong nâng cao trải nghiệm khách hàng và tối ưu hóa vận hành bán lẻ.',
  },
];
