export interface OrganizationLogo {
  id: string;
  name: string;
  shortName?: string;
  industryId: 'finance' | 'real-estate' | 'tech-edu' | 'media' | 'fmcg' | 'logistics' | 'retail';
  industryName: string;
  tier: 1 | 2;
  caseStudySlug?: string;
  logoUrl: string;
  brandColor: string;
  brandBg: string;
  description: string;
}

export interface IndustryFilter {
  id: string;
  name: string;
  count?: number;
}

export const INDUSTRY_FILTERS: IndustryFilter[] = [
  { id: 'all', name: 'Tất Cả Ngành' },
  { id: 'finance', name: 'Tài Chính · Chứng Khoán · Bảo Hiểm' },
  { id: 'real-estate', name: 'Bất Động Sản · Năng Lượng · Công Nghiệp' },
  { id: 'tech-edu', name: 'Công Nghệ · Giáo Dục Đại Học' },
  { id: 'media', name: 'Truyền Thông · Sáng Tạo' },
  { id: 'fmcg', name: 'FMCG · F&B · Dược Phẩm' },
  { id: 'logistics', name: 'Vận Tải · Logistics · Phân Phối' },
  { id: 'retail', name: 'Bán Lẻ Chuỗi & Thương Mại' },
];

export const ORGANIZATION_LOGOS: OrganizationLogo[] = [
  // 1. Vietcap Securities
  {
    id: 'vietcap',
    name: 'Vietcap Securities (VCI)',
    shortName: 'Vietcap',
    industryId: 'finance',
    industryName: 'Tài Chính & Chứng Khoán',
    tier: 1,
    caseStudySlug: 'vietcap-ai-multi-agent-nghien-cuu-thi-truong',
    logoUrl: '/logos/vietcap.png',
    brandColor: '#005596',
    brandBg: '#F0F5FA',
    description: 'Thiết lập hệ thống Multi-Agent bóc tách BCTC tự động cho 30+ chuyên viên, giảm 75% thời gian xử lý.',
  },
  // 2. Vinhomes
  {
    id: 'vinhomes',
    name: 'Vinhomes (Vingroup)',
    shortName: 'Vinhomes',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 1,
    caseStudySlug: 'vinhomes-ai-sales-enablement',
    logoUrl: '/logos/vinhomes.png',
    brandColor: '#8B6F3E',
    brandBg: '#FBF8F3',
    description: 'Đào tạo AI Sales Enablement & Lead Reactivation cho 500+ nhân sự kinh doanh và phân phối BĐS.',
  },
  // 3. FPT University
  {
    id: 'fptu',
    name: 'Đại học FPT (FPTU)',
    shortName: 'ĐH FPT',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 1,
    caseStudySlug: 'fptu-nang-bac-giang-vien-ai',
    logoUrl: '/logos/fptu.png',
    brandColor: '#F37021',
    brandBg: '#FEF5EE',
    description: 'Đào tạo nâng bậc GV chuẩn Bậc 6 & Điều phối MC ảo và AI Agents tại Tech Fest với 10.000+ người tham gia.',
  },
  // 4. Dentsu Sports Vietnam
  {
    id: 'dentsu',
    name: 'Dentsu Sports & Creative',
    shortName: 'Dentsu',
    industryId: 'media',
    industryName: 'Truyền Thông & Sáng Tạo',
    tier: 1,
    caseStudySlug: 'dentsu-ai-pitch-deck-automation',
    logoUrl: '/logos/dentsu.png',
    brandColor: '#002D62',
    brandBg: '#EFF4F9',
    description: 'Rút ngắn 65% thời gian phát triển proposal đấu thầu tài trợ thể thao quốc tế bằng quy trình AI chuẩn hóa.',
  },
  // 5. VNPT VinaPhone
  {
    id: 'vnpt',
    name: 'VNPT VinaPhone',
    shortName: 'VNPT',
    industryId: 'tech-edu',
    industryName: 'Viễn Thông & Dịch Vụ Số',
    tier: 1,
    caseStudySlug: 'vnpt-ai-content-video-automation',
    logoUrl: '/logos/vnpt_vinaphone.png',
    brandColor: '#0066B2',
    brandBg: '#EDF5FC',
    description: 'Tăng gấp 3 lần sản lượng nội dung truyền thông số và video ngắn giới thiệu gói cước tự động.',
  },
  // 6. Phương Trường An Group
  {
    id: 'phuong-truong-an',
    name: 'Phương Trường An Group',
    shortName: 'Phương Trường An',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 1,
    caseStudySlug: 'phuong-truong-an-ai-video-production',
    logoUrl: '/logos/phuong_truong_an.png',
    brandColor: '#0A5C36',
    brandBg: '#EDF7F1',
    description: 'Đào tạo sản xuất video hiện trường bằng AI, tăng 200% sản lượng tin bài cho ~300 nhân sự kinh doanh.',
  },
  // 7. Trương Đoàn Marketing Group
  {
    id: 'truong-doan',
    name: 'Trương Đoàn Marketing Group',
    shortName: 'Trương Đoàn',
    industryId: 'media',
    industryName: 'Tiếp Thị & Activation',
    tier: 1,
    caseStudySlug: 'truong-doan-ai-activation-qc',
    logoUrl: '/logos/truong_doan.png',
    brandColor: '#E02B20',
    brandBg: '#FDF1F0',
    description: 'Tiết kiệm 70% thời gian duyệt ảnh thực địa activation và rút ngắn phản hồi brief từ 3 ngày xuống 4 giờ.',
  },
  // 8. Đài Truyền Hình TP.HCM (HTV)
  {
    id: 'htv',
    name: 'Đài Truyền Hình TP.HCM (HTV)',
    shortName: 'HTV',
    industryId: 'media',
    industryName: 'Truyền Hình & Phát Thanh',
    tier: 1,
    logoUrl: '/logos/htv.png',
    brandColor: '#0088CC',
    brandBg: '#EDF8FD',
    description: 'Rút ngắn 50% thời gian sản xuất đồ họa trường quay ảo và tự động hóa dựng trailer phát sóng.',
  },
  // 9. Smartland Bất Động Sản
  {
    id: 'smartland',
    name: 'Smartland Bất Động Sản',
    shortName: 'Smartland',
    industryId: 'real-estate',
    industryName: 'Phân Phối BĐS Cao Cấp',
    tier: 1,
    logoUrl: '/logos/smartland.png',
    brandColor: '#B8860B',
    brandBg: '#FDFBF0',
    description: 'Tự động hóa 80% khâu tương tác ban đầu với khách hàng tiềm năng dự án căn hộ cao cấp qua AI Agents.',
  },
  // 10-13. Vietcombank, BIDV, Prudential, Dai-ichi Life Vietnam:
  // Gỡ tạm khỏi lưới logo công khai — nhóm ngân hàng/bảo hiểm cần xác nhận
  // bằng văn bản trước khi dùng logo, chưa có xác nhận tại thời điểm này.
  // Xem site-fix-plan/06_DANH_GIA_TOAN_DIEN_SAU_TICH_HOP_LOGO.md mục 5.
  // 14. Trung Sơn Pharma
  {
    id: 'trung-son',
    name: 'Trung Sơn Pharma',
    shortName: 'Trung Sơn',
    industryId: 'fmcg',
    industryName: 'Chuỗi Bán Lẻ Dược Phẩm',
    tier: 1,
    logoUrl: '/logos/trung_son.png',
    brandColor: '#0077C8',
    brandBg: '#EDF6FC',
    description: 'Tư vấn thiết kế hệ thống Omnichannel Marketing & CRM chuỗi nhà thuốc từ giai đoạn mở rộng mạng lưới.',
  },
  // 15. FSI Digital
  {
    id: 'fsi',
    name: 'FSI Digital',
    shortName: 'FSI',
    industryId: 'tech-edu',
    industryName: 'Chuyển Đổi Số & Dữ Liệu',
    tier: 2,
    logoUrl: '/logos/fsi.png',
    brandColor: '#004B87',
    brandBg: '#EEF4F9',
    description: 'Nhân sự tham gia chương trình đào tạo AI trong số hóa dữ liệu và xử lý văn bản phi cấu trúc.',
  },
  // 16. Droppii Commerce
  {
    id: 'droppii',
    name: 'Droppii Commerce',
    shortName: 'Droppii',
    industryId: 'tech-edu',
    industryName: 'Thương Mại Điện Tử Tư Vấn',
    tier: 2,
    logoUrl: '/logos/droppii.png',
    brandColor: '#FF5500',
    brandBg: '#FEF4EE',
    description: 'Đào tạo AI ứng dụng trong tự động hóa kịch bản tư vấn và sáng tạo nội dung livestream thương mại.',
  },
  // 17. UEF
  {
    id: 'uef',
    name: 'Đại học Kinh tế - Tài chính TP.HCM (UEF)',
    shortName: 'UEF',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 2,
    logoUrl: '/logos/uef.png',
    brandColor: '#C8102E',
    brandBg: '#FCF0F2',
    description: 'Tổ chức các chuyên đề ứng dụng AI trong thực tế và đào tạo kỹ năng ứng dụng công nghệ cho sinh viên & giảng viên.',
  },
  // 18. NTTU
  {
    id: 'nttu',
    name: 'Đại học Nguyễn Tất Thành (NTTU)',
    shortName: 'NTTU',
    industryId: 'tech-edu',
    industryName: 'Giáo Dục Đại Học',
    tier: 2,
    logoUrl: '/logos/nguyen_tat_thanh.png',
    brandColor: '#003865',
    brandBg: '#EDF3F8',
    description: 'Hợp tác chuyển giao kiến thức AI thực hành và xây dựng kỹ năng công nghệ chuẩn bị cho thị trường lao động.',
  },
  // 19. Thắng Lợi Group
  {
    id: 'thang-loi',
    name: 'Thắng Lợi Group',
    shortName: 'Thắng Lợi',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 2,
    logoUrl: '/logos/thang_loi_group.png',
    brandColor: '#C29B38',
    brandBg: '#FCF9F1',
    description: 'Chuyên viên kinh doanh tham gia đào tạo AI sáng tạo nội dung dự án và chăm sóc khách hàng tự động.',
  },
  // 20. Huỳnh Anh Group
  {
    id: 'huynh-anh',
    name: 'Huỳnh Anh Group',
    shortName: 'Huỳnh Anh',
    industryId: 'real-estate',
    industryName: 'Bất Động Sản',
    tier: 2,
    logoUrl: '/logos/huynh_anh.png',
    brandColor: '#2E5B88',
    brandBg: '#F0F4F8',
    description: 'Đào tạo ứng dụng AI trong quản lý leads và tự động hóa quy trình phân phối sản phẩm bất động sản.',
  },
  // 21. PV Power
  {
    id: 'pv-power',
    name: 'PV Power',
    shortName: 'PV Power',
    industryId: 'real-estate',
    industryName: 'Năng Lượng & Điện Lực',
    tier: 2,
    logoUrl: '/logos/pv_power.png',
    brandColor: '#007A3D',
    brandBg: '#EDF7F2',
    description: 'Cán bộ kỹ thuật và quản lý tham gia đào tạo phương pháp luận AI trong quản trị dữ liệu vận hành.',
  },
  // 22. Mì Gấu Đỏ
  {
    id: 'gau-do',
    name: 'Mì Gấu Đỏ (Asia Foods)',
    shortName: 'Gấu Đỏ',
    industryId: 'fmcg',
    industryName: 'FMCG & Thực Phẩm',
    tier: 2,
    logoUrl: '/logos/gau_do.png',
    brandColor: '#E31E24',
    brandBg: '#FDF1F1',
    description: 'Cán bộ tiếp thị tham gia chương trình nâng cao năng lực AI trong tiếp thị tiêu dùng và phân tích dữ liệu.',
  },
  // 23. Cháo Cây Thị
  {
    id: 'cay-thi',
    name: 'Cháo Cây Thị',
    shortName: 'Cây Thị',
    industryId: 'fmcg',
    industryName: 'F&B & Thực Phẩm Dinh Dưỡng',
    tier: 2,
    logoUrl: '/logos/cay_thi.png',
    brandColor: '#F37021',
    brandBg: '#FEF5EE',
    description: 'Đào tạo AI ứng dụng trong tối ưu hóa nội dung đa kênh và quản trị thương hiệu chuỗi thực phẩm.',
  },
  // 24. Yến Việt
  {
    id: 'yen-viet',
    name: 'Yến Việt',
    shortName: 'Yến Việt',
    industryId: 'fmcg',
    industryName: 'FMCG & Dinh Dưỡng',
    tier: 2,
    logoUrl: '/logos/yen_viet.png',
    brandColor: '#9A1B24',
    brandBg: '#FAF1F2',
    description: 'Nhân sự tham gia đào tạo AI trong quản trị phân phối, kiểm soát nội bộ và tiếp thị chuỗi giá trị.',
  },
  // 25. Dr. Muối
  {
    id: 'dr-muoi',
    name: 'Dr. Muối',
    shortName: 'Dr. Muối',
    industryId: 'fmcg',
    industryName: 'Sức Khỏe & Tiêu Dùng',
    tier: 2,
    logoUrl: '/logos/dr_muoi.png',
    brandColor: '#00A3E0',
    brandBg: '#EDF9FD',
    description: 'Chuyên viên Marketing tham gia đào tạo AI tự động hóa sản xuất nội dung quảng cáo và video đa kênh.',
  },
  // 26. Hoàng Đức Pharma
  {
    id: 'hoang-duc',
    name: 'Hoàng Đức Pharma',
    shortName: 'Hoàng Đức',
    industryId: 'fmcg',
    industryName: 'Phân Phối Dược Phẩm',
    tier: 2,
    logoUrl: '/logos/hoang_duc_pharma.png',
    brandColor: '#008542',
    brandBg: '#EDF8F2',
    description: 'Cán bộ phân phối tham gia đào tạo ứng dụng AI trong chăm sóc mạng lưới đối tác nhà thuốc.',
  },
  // 27. Agrilong
  {
    id: 'agrilong',
    name: 'Agrilong',
    shortName: 'Agrilong',
    industryId: 'fmcg',
    industryName: 'Nông Nghiệp & Vật Tư',
    tier: 2,
    logoUrl: '/logos/agrilong.png',
    brandColor: '#2E7D32',
    brandBg: '#EFF7F0',
    description: 'Nhân sự tiếp thị tham gia đào tạo AI xây dựng nội dung truyền thông kỹ thuật nông nghiệp.',
  },
  // 28. VAG International (Poêmy)
  {
    id: 'poemy',
    name: 'VAG International (Poêmy)',
    shortName: 'Poêmy',
    industryId: 'fmcg',
    industryName: 'Dệt May & Tiêu Dùng',
    tier: 2,
    logoUrl: '/logos/vag_international.png',
    brandColor: '#4A154B',
    brandBg: '#F5EFF5',
    description: 'Đội ngũ bán hàng tham gia đào tạo AI trong sáng tạo hình ảnh sản phẩm và tối ưu hóa sàn TMĐT.',
  },
  // 29. Big Family
  {
    id: 'big-family',
    name: 'Big Family',
    shortName: 'Big Family',
    industryId: 'fmcg',
    industryName: 'Chuỗi Nhà Thuốc',
    tier: 2,
    logoUrl: '/logos/big_family.png',
    brandColor: '#D8232A',
    brandBg: '#FCF1F2',
    description: 'Học viên tham gia đào tạo AI hỗ trợ chăm sóc khách hàng và quản trị nội dung tư vấn sức khỏe.',
  },
  // 30. Maison Vie
  {
    id: 'maison-vie',
    name: 'Maison Vie',
    shortName: 'Maison Vie',
    industryId: 'fmcg',
    industryName: 'F&B & Ẩm Thực Cao Cấp',
    tier: 2,
    logoUrl: '/logos/maison_vie.png',
    brandColor: '#8C6239',
    brandBg: '#F9F5F1',
    description: 'Cán bộ quản lý ẩm thực tham gia đào tạo AI trong xây dựng trải nghiệm khách hàng và truyền thông ẩm thực.',
  },
  // 31. VACS
  {
    id: 'vacs',
    name: 'VACS (Suất Ăn Hàng Không)',
    shortName: 'VACS',
    industryId: 'logistics',
    industryName: 'Suất Ăn & Logistics Hàng Không',
    tier: 2,
    logoUrl: '/logos/vacs.png',
    brandColor: '#003865',
    brandBg: '#EDF3F8',
    description: 'Nhân sự logistics tham gia đào tạo AI trong chuẩn hóa tài liệu SOP và báo cáo quy trình tác nghiệp.',
  },
  // 32. Mitsubishi Motors
  {
    id: 'mitsubishi',
    name: 'Mitsubishi Motors',
    shortName: 'Mitsubishi',
    industryId: 'logistics',
    industryName: 'Phân Phối Ô Tô',
    tier: 2,
    logoUrl: '/logos/mitsubishi_motors.png',
    brandColor: '#E60012',
    brandBg: '#FDF0F1',
    description: 'Chuyên viên đại lý tham gia chương trình đào tạo AI trong chăm sóc khách hàng và tiếp thị số.',
  },
  // 33. QH Distribution
  {
    id: 'qh-dist',
    name: 'QH Distribution',
    shortName: 'QH Dist.',
    industryId: 'logistics',
    industryName: 'Phân Phối Chuỗi',
    tier: 2,
    logoUrl: '/logos/qh_distribution.png',
    brandColor: '#1A365D',
    brandBg: '#EEF2F7',
    description: 'Đội ngũ quản lý tham gia đào tạo AI trong phân tích dữ liệu phân phối và quản trị chuỗi cung ứng.',
  },
  // 34. PTEXIM Corp
  {
    id: 'ptexim',
    name: 'PTEXIM Corp',
    shortName: 'PTEXIM',
    industryId: 'logistics',
    industryName: 'Xuất Nhập Khẩu Nông Sản',
    tier: 2,
    logoUrl: '/logos/ptexim.png',
    brandColor: '#8B0000',
    brandBg: '#F9EEEE',
    description: 'Cán bộ xuất khẩu tham gia đào tạo AI trong soạn thảo hợp đồng thương mại quốc tế và nghiên cứu thị trường.',
  },
  // 35. Let's Go Taxi
  {
    id: 'lets-go-taxi',
    name: "Let's Go Taxi",
    shortName: "Let's Go",
    industryId: 'logistics',
    industryName: 'Vận Tải Hành Khách',
    tier: 2,
    logoUrl: '/logos/lgo_taxi.png',
    brandColor: '#F7941D',
    brandBg: '#FEF7F0',
    description: 'Đội ngũ vận hành tham gia đào tạo AI trong xử lý dữ liệu dịch vụ và chăm sóc đối tác tài xế tự động.',
  },
  // 36. JTB-TNT Travel
  {
    id: 'jtb-tnt',
    name: 'JTB-TNT Travel',
    shortName: 'JTB-TNT',
    industryId: 'logistics',
    industryName: 'Du Lịch & Lữ Hành Quốc Tế',
    tier: 2,
    logoUrl: '/logos/jtb_tnt.png',
    brandColor: '#CC0000',
    brandBg: '#FCEEEE',
    description: 'Chuyên viên du lịch tham gia đào tạo AI xây dựng kịch bản tour quốc tế và chăm sóc khách du lịch số.',
  },
  // 37. Golden Gate Group
  {
    id: 'golden-gate',
    name: 'Golden Gate Group',
    shortName: 'Golden Gate',
    industryId: 'fmcg',
    industryName: 'Chuỗi Ẩm Thực F&B',
    tier: 2,
    logoUrl: '/logos/golden_gate.png',
    brandColor: '#B8860B',
    brandBg: '#FDFBF0',
    description: 'Học viên và chuyên gia tham gia chia sẻ kinh nghiệm ứng dụng AI trong quản trị chuỗi 300+ nhà hàng.',
  },
  // 38. Carlsberg Group
  {
    id: 'carlsberg',
    name: 'Carlsberg Group',
    shortName: 'Carlsberg',
    industryId: 'fmcg',
    industryName: 'Đồ Uống & Tiêu Dùng',
    tier: 2,
    logoUrl: '/logos/carlsberg.png',
    brandColor: '#006F42',
    brandBg: '#ECF6F1',
    description: 'Học viên và cố vấn tham gia chia sẻ phương pháp luận AI trong quản trị thương hiệu đồ uống toàn cầu.',
  },
  // 39. Con Cưng
  {
    id: 'con-cung',
    name: 'Con Cưng',
    shortName: 'Con Cưng',
    industryId: 'retail',
    industryName: 'Bán Lẻ Mẹ & Bé',
    tier: 2,
    logoUrl: '/logos/con_cung.png',
    brandColor: '#E4002B',
    brandBg: '#FDF0F2',
    description: 'Đào tạo ứng dụng AI trong chăm sóc khách hàng đa kênh và tối ưu hóa vận hành bán lẻ chuỗi.',
  },
  // 40. Shopee
  {
    id: 'shopee',
    name: 'Shopee',
    shortName: 'Shopee',
    industryId: 'retail',
    industryName: 'Sàn TMĐT Đa Kênh',
    tier: 2,
    logoUrl: '/logos/shopee.png',
    brandColor: '#EE4D2D',
    brandBg: '#FEF3F0',
    description: 'Học viên tham gia đào tạo AI trong sáng tạo nội dung sản phẩm, livestream và tối ưu hóa chuyển đổi.',
  },
  // 41. Lazada
  {
    id: 'lazada',
    name: 'Lazada Vietnam',
    shortName: 'Lazada',
    industryId: 'retail',
    industryName: 'Sàn TMĐT Quốc Tế',
    tier: 2,
    logoUrl: '/logos/lazada.png',
    brandColor: '#0F146D',
    brandBg: '#EFF0F8',
    description: 'Học viên tham gia các khóa đào tạo AI Marketing & ứng dụng Prompt Engineering theo nghiệp vụ.',
  },
  // 42. Tiki
  {
    id: 'tiki',
    name: 'Tiki',
    shortName: 'Tiki',
    industryId: 'retail',
    industryName: 'Thương Mại Điện Tử',
    tier: 2,
    logoUrl: '/logos/tiki.png',
    brandColor: '#1A94FF',
    brandBg: '#F0F7FF',
    description: 'Học viên tham gia đào tạo ứng dụng AI trong phân tích dữ liệu mua sắm và chăm sóc khách hàng.',
  },
  // 43. Hòa Phát
  {
    id: 'hoa-phat',
    name: 'Tập đoàn Hòa Phát',
    shortName: 'Hòa Phát',
    industryId: 'real-estate',
    industryName: 'Thép & Công Nghiệp Nặng',
    tier: 2,
    logoUrl: '/logos/hoa_phat.png',
    brandColor: '#003A70',
    brandBg: '#EDF3F8',
    description: 'Đề án đào tạo nâng cao năng lực ứng dụng AI vào công việc cho cán bộ quản lý và khối tác nghiệp.',
  },
  // 44. HOSE (Sở GDCK TP.HCM): gỡ tạm — cơ quan bán nhà nước, cần xác nhận
  // trước khi dùng logo dù chỉ để minh họa lý lịch cá nhân của cố vấn.
  // Xem site-fix-plan/06_DANH_GIA_TOAN_DIEN_SAU_TICH_HOP_LOGO.md mục 5.
  // 45. Bamboo Capital
  {
    id: 'bamboo-capital',
    name: 'Bamboo Capital Group',
    shortName: 'Bamboo Capital',
    industryId: 'real-estate',
    industryName: 'Tập Đoàn Đa Ngành',
    tier: 2,
    logoUrl: '/logos/bamboo_capital.png',
    brandColor: '#008542',
    brandBg: '#EDF8F2',
    description: 'Cố vấn tài chính Sunext nguyên Giám đốc Tài chính (CFO) Aurai Wind Energy (cụm dự án điện gió 550MW).',
  },
  // 46. VinaCapital
  {
    id: 'vinacapital',
    name: 'VinaCapital Group',
    shortName: 'VinaCapital',
    industryId: 'finance',
    industryName: 'Quản Lý Quỹ Đầu Tư',
    tier: 2,
    logoUrl: '/logos/vinacapital.png',
    brandColor: '#981E32',
    brandBg: '#FAF1F3',
    description: 'Chuyên gia tài chính Sunext (Lê Thị Cẩm Vân) từng giữ trọng trách quản trị tại các doanh nghiệp có vốn góp VinaCapital.',
  },
  // 47. Talentnet
  {
    id: 'talentnet',
    name: 'Talentnet Corporation',
    shortName: 'Talentnet',
    industryId: 'tech-edu',
    industryName: 'Tư Vấn Nhân Sự & Lãnh Đạo',
    tier: 2,
    logoUrl: '/logos/talentnet.png',
    brandColor: '#004B87',
    brandBg: '#EEF4F9',
    description: 'Hợp tác đào tạo và chia sẻ phương pháp luận AI trong nâng cao năng suất quản trị nguồn nhân lực.',
  },
  // 48. TechX Cloud
  {
    id: 'techx',
    name: 'TechX Cloud',
    shortName: 'TechX',
    industryId: 'tech-edu',
    industryName: 'Điện Toán Đám Mây & AI',
    tier: 2,
    logoUrl: '/logos/techx.png',
    brandColor: '#0066CC',
    brandBg: '#EDF5FC',
    description: 'Đồng hành chuyển giao giải pháp AI kiến trúc đám mây và tối ưu hóa hạ tầng dữ liệu doanh nghiệp.',
  },
  // 49. Tetra Pak
  {
    id: 'tetra-pak',
    name: 'Tetra Pak',
    shortName: 'Tetra Pak',
    industryId: 'fmcg',
    industryName: 'Bao Bì & Chế Biến Thực Phẩm',
    tier: 2,
    logoUrl: '/logos/tetra_pak.png',
    brandColor: '#003A70',
    brandBg: '#EDF3F8',
    description: 'Chia sẻ thực tiễn ứng dụng AI trong quản trị chuỗi cung ứng và tự động hóa quy trình sản xuất thực phẩm.',
  },
  // 50. Hải Sản Hoàng Gia
  {
    id: 'hai-san-hoang-gia',
    name: 'Hải Sản Hoàng Gia',
    shortName: 'Hải Sản Hoàng Gia',
    industryId: 'fmcg',
    industryName: 'Chuỗi Bán Lẻ & Nhà Hàng',
    tier: 2,
    logoUrl: '/logos/hai_san_hoang_gia.png',
    brandColor: '#D32F2F',
    brandBg: '#FDF1F1',
    description: 'Cố vấn nhân sự và marketing Sunext từng trực tiếp quản trị hệ thống vận hành và tiếp thị chuỗi.',
  },
];
